import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});
export function TopNav() {
  return (
    <header className="w-full border-b border-gray-200 p-4 px-4 text-xl font-semibold sm:px-6">
      {" "}
      <nav className="flex w-full justify-between">
        <div>Gallery</div>
        <div>Sign In</div>
      </nav>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} bg-gray-800 text-white`}>
      <body>
        <TopNav />
        {children}
      </body>
    </html>
  );
}
